#!/usr/bin/env bash

cd $SRC_DIR/base16-builder/output/guake/
TAB="\t"

if [ $# -eq 1 ]; then
  if [ $1 = --list ]; then

    echo "Available themes are:"
    command ls && exit 0

  elif [ $1 = --generate ];then

    cd ../../ && ./base16 && exit 0

  elif [ $1 = --help ]; then
    echo -e "Available options are:"
    echo -e "${TAB}--list${TAB}${TAB} Shows currently available themes"
    echo -e "${TAB}--generate${TAB} Compile all themes"
    echo -e "${TAB}--help${TAB}${TAB} Shows this help menu"
    exit 0
  fi
fi

SCHEME_PREFIX=base16-
DEFAULT_SCHEME=ocean
SCHEME="${SCHEME_PREFIX}${1:-$DEFAULT_SCHEME}"
BACKGROUND_VERSION=${2:-dark}


scheme_script="${SCHEME}.${BACKGROUND_VERSION}.sh"

if [ ! -e $scheme_script ]; then
  echo "Required scheme (${scheme_script}) not found."
  exit 1
fi

[ ! -x $scheme_script ] && chmod +x $scheme_script

./${scheme_script}
